### PR TITLE
added links to featured cards

### PR DESCRIPTION
**Pull request by Oceantidote**

### CODE REVIEW

**Comment by dujaje** [comment]
changing the name of the css selector to featured kitchens card is going to fuck with some other pages, do we neeeeed tooo?

**Comment by Oceantidote** [comment]
The original ccs selector is still there so it shouldn't fuck over any other code.
I just added another one that's all.

**Comment by Oceantidote** [comment]
Which page will it cause issues with?

**Comment by dujaje** [comment]
kk - why the need for 2?

I'll take a look once its added

**Pull request merged**
